name: "Apply_TF_Plan"
on: 
  push
jobs:
  TF_Plan_Dev:
    uses: ./.github/workflows/tf_plan.yml
    with:
      path: app/
      tf_vars_file: dev.tfvars
    secrets: 
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  